version: '3'

services:

  hbase:
    image: harisekhon/hbase:1.4o
    ports:
      - 9090:9090
      - 9095:9095
      - 2181:2181
      - 16201:16201
    container_name: hbase

  metadatastore:
    image: mysql:5.7
    restart: always
    container_name: metadatastore
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "dummy_database"
      MYSQL_USER: "dummy_user"
      MYSQL_PASSWORD: "user_password"
